### ISSUE TITLE
:LiveServerStart Freezes Neovim

### ISSUE THREAD

**Issue by ZackBz** [barrett-ruth/live-server.nvim#11]
I believe that I have the correct setup from the docs. I am using Lazy and Bun though. This is my setup:

```lua
{
  "barrett-ruth/live-server.nvim",
  build = { "bun add -g live-server@1.2.1" },
  cmd = { "LiveServerStart", "LiveServerStop" },
  config = true,
},
```

Some more context: I can run `live-server .` in my project dir and live-server will start or i can run `bunx live-server .` in my project dir which will also start live-server. The reason for 1.2.1 is because of an issue with Live Server and Linux on the latest version. I have run `:checkhealth` and everything seems fine as far as I can tell. However, if i run the command, `:LiveServerStart` within Neovim, it will freeze and become unresponsive so I need to close and reopen it.

I have a feeling I maybe reconfigured something and I don't see it. TIA!

**Comment by barrett-ruth** [comment]
Attempt to replicate the issue with other package managers - ensure the live server executable being found is not that of bun while doing so.

Thanks for reporting!

**Comment by barrett-ruth** [comment]
@ZackBz reopen if this is still happening
