### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by elementtest** [barrett-ruth/live-server.nvim#13]
### Info

- Operating System: Ubuntu
- `nvim --version`: v.0.11.0
- Node package manager: v21.7.3
- `<node-package-manager> --version`: v21.7.3
- `live-server --version`: 1.2.2

### Configuration

return {
        'barrett-ruth/live-server.nvim',
        build = 'pnpm add -g live-server',
        cmd = { 'LiveServerStart', 'LiveServerStop' },
        config = true
    }

```lua
require('nvim-package-manager').setup {
    -- Any special plugin config
    {
        'barrett-ruth/live-server.nvim',
    }
}
```

</details>

### Description

When I run :LiveServerStart command in neovim it is giving me error:  

Cannot GET /

**Comment by elementtest** [comment]
I think I've narrowed the problem down a bit.  It seems to be stemming from this when i open developer tools in the browser:  
Content-Security-Policy: The page’s settings blocked the loading of a resource (img-src) at http://127.0.0.1:5555/favicon.ico because it violates the following directive: “default-src 'none'”.

When I use the live-server command in the terminal there is no problem.  Only when using this plugin do i encoutner the issue

**Comment by elementtest** [comment]
seems the most recent update fde21e3 is causing the "Cannot GET /" issue for me.

**Comment by barrett-ruth** [comment]
Can you replicate the issue please, given the files, directory locations, and cmds you run in neovim? Thanks

**Comment by elementtest** [comment]
To replicate issue opened up simple index.html file with boiler plate and ran :LiveServerStart in neovim. This issue only happens with repo's latest commit fde21e3

**Comment by elementtest** [comment]
To replicate issue opened up simple index.html file with boiler plate HTML and ran :LiveServerStart in neovim. This issue only happens with repo's latest commit

**Comment by barrett-ruth** [comment]
should be fixed in most recent commit

**Comment by elementtest** [comment]
works now, thank you
