### ISSUE TITLE
Not working in window's

### ISSUE THREAD

**Issue by NormTurtle** [barrett-ruth/live-server.nvim#2]
### Info

- Operating System: window 11
- nvim : 0.9.1
- node -v = v20.3.0
- `live-server --version`: 1.2.2
- 
### Configuration
default for liveserver.nvim

LAZY
```lua
require('lazy').setup {
    {
        'barrett-ruth/live-server.nvim',
        build = 'yarn global add live-server',
        config = true
    },
}
```

</details>

### Description

when running `:liveserverstart` neoivm just freezez heck it freezes whole terminal 
![image](https://github.com/barrett-ruth/live-server.nvim/assets/108952834/9bbc0f6a-d722-4fb9-ba45-a8e69d7e80eb)

**Comment by Ontropy** [comment]
Exact same issue for me. I am on windows 10 and using npm. Everything freezes on running LiveServerStart

**Comment by barrett-ruth** [comment]
Not to be terse, but this plugin is not meant to support windows. I don't have a windows laptop and frankly don't have time to delve into the dumpster fire that is neovim with windows. However, if you provide any logs or *legitimate* ways to help you debug I will do my best. Closing this for now.
