### ISSUE TITLE
live-server not reloading browser

### ISSUE THREAD

**Issue by SamuelCano03** [barrett-ruth/live-server.nvim#4]
### Info
I downloaded live-server for nvim with lazy. also globally with npm. It works when running `LiveServerStart`, but saved changes are not reloaded in the browser. I have to manually reload the browser to see the changes. 
- Operating System: Ubuntu22.04
- `nvim --version`: v0.9.4
- Node package manager: 
- `<node-package-manager> --version`: nvm 0.38.0
- `live-server --version`: 1.2.2

### Configuration

this is my config located in custom.plugins.lua (I'm using nvchad distro of nvim):
```
{
        "barrett-ruth/live-server.nvim",
        build = "npm install -g live-server",
        event={"BufReadPre", "BufNewFile"}, --this is for initiate live-server in new buffer
        config=true,
     },
```

</details>
this is what console in browser shows: `Live reload enabled.`

### Description
Another thing i noticed, is when running LiveServerStop, i got this message: `live-server.nvim: stopped with code 143`
Even If I don't make any change to the html file, i got that message when running LiveServerStop.

This is my html file if it is important 
```
<!DOCTYPE html>
<html lang="en">
     <head>
          <title></title>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <!-- <link href="css/style.css" rel="stylesheet"> -->
     </head>
     <body>
          <h1>Hi</h1> 
     </body>
</html>

``` 
It was working very well before, I don't know what happened :'/

**Comment by barrett-ruth** [comment]
Two things:

1. can you give me more information on your operating system, browser, etc.
2. can you try this configuration again but remove the `event` field from the lazy configuration.
3. run `live-server .` yourself and open up the browser on the file you're working on. if that doesn't work, then it is a problem with liver-server and not live-server.nvim. If the file you're working on is indeed the one being rendered in the browser, a failure to update is probably not coming from live-server.

**Comment by SamuelCano03** [comment]
Yes sir and thank you for your response and your time. Here you have the specs:

> 1. can you give me more information on your operating system, browser, etc.

- Operating System (`uname -a`) : `Linux Lenova 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
- Browser: *Brave* 1.61.116 Chromium: 120.0.6099.217 (Official Build) (64-bit) 

> 2. can you try this configuration again but remove the `event` field from the lazy configuration.

- I have removed the `event` field, but the issue persists.

> 3. run `live-server .` yourself and open up the browser on the file you're working on. if that doesn't work, then it is a problem with liver-server and not live-server.nvim. If the file you're working on is indeed the one being rendered in the browser, a failure to update is probably not coming from live-server.

- I runned `live-server .` and everything was working OK even with and without the `event` field in lazy config. (I've been previously trying with `live-server` without the '.' and it didn't reload the browser for new changes, the same issue with `:LiveServerStart`). Even tho, the command `:LiveServerStart` for nvim is not working. I will be using `live-server .` in the terminal but I'll be waiting for a response for the issue too so if you need more details I'll be aware :)

**Comment by SamuelCano03** [comment]
I've reinstalled the plugin with the new configurations. I don't use pnpm but I've tried to build the plugin with it without success, so I did it with npm. The live-server stopped message is updated. The issue persists tho. 

```
 {
        "barrett-ruth/live-server.nvim",
        build = "npm install -g live-server",
        cmd = { 'LiveServerStart', 'LiveServerStop' },
        -- event={"BufReadPre", "BufNewFile"},
        config=true,
},
```

the output when I do `:echo executable('live-server')` is 1. 

This is the log of Lazy:

![image](https://github.com/barrett-ruth/live-server.nvim/assets/102400537/3c090fed-775d-4e95-90d2-48e0bd1853b8)

**Comment by barrett-ruth** [comment]
Sorry about this bug, it is really confounding. Take for example below, where I start the live-server via `:LiveServerStart` then view the process and see it is running with `ps aux | grep live-server`. So, you are saying if you start live-server via the CLI, the browser reflects changes, but via live-server.nvim, it doesn't?

If that's the case, then try to replicate the setup below:
<img width="1511" alt="image" src="https://github.com/barrett-ruth/live-server.nvim/assets/62671086/9edfd956-072e-42b2-b2d9-a23c46e3197f">

Lastly, the plugin is only about 100 lines long, so debug on your own if you're willing (I should probably add a debug mode myself).

**Comment by SamuelCano03** [comment]
I've recorded my screen so you can see more clearly how the bug is. As you can see, using `:LiveStartServer` and `live-server` have the same bug (I need to reload the browser to see changes). But running `live-server .`  works fine. 

https://github.com/barrett-ruth/live-server.nvim/assets/102400537/b1faf6d3-8999-419b-b4a9-062188e8a902

This is the output of `ps aux | grep live-server` when running `:LiveStartServer` 

![image](https://github.com/barrett-ruth/live-server.nvim/assets/102400537/fe348b97-57ba-4e9d-8e46-81fb097ec2ab)

This is the output when running `live-server .`

![image](https://github.com/barrett-ruth/live-server.nvim/assets/102400537/a06f7783-0e02-4239-b363-1d1083cd95e3)


Hope the bug is clearer now.

**Comment by barrett-ruth** [comment]
@SamuelCano03 thanks for the video that is actually helpful.

Can you also run `live-server /home/samuelDesktop/.proy` from the command line and see if the browser will reload?

gracias :D

**Comment by SamuelCano03** [comment]
The same issue, browser doesn't reload. 

If it is important, here is the output of ps aux | grep live-server

![image](https://github.com/barrett-ruth/live-server.nvim/assets/102400537/db1aa4c6-1533-4df1-b8c6-dea8a016e503)

This is what I see when pressing f12 in browser:

![image](https://github.com/barrett-ruth/live-server.nvim/assets/102400537/cb2e2207-7b84-4362-b162-19a72294b828)

This is the output of the console of the browser:

![image](https://github.com/barrett-ruth/live-server.nvim/assets/102400537/9b9e4208-5164-4ab4-a4ac-341f26171f6b)

**Comment by barrett-ruth** [comment]
it's because the directory is hidden. I replicated the issue using a hidden `.proy` directory, and the issue went away using a non-hidden directory. I suggest you do not work on major projects using hidden directories - that doesn't seem to make much sense. Otherwise, report the issue with the live-server package directly.

I definitely should've caught this issue earlier - sorry for how long this took to debug. Let me know if you have any other comments, but I don't think there's anything on live-server.nvim's end to change.

**Comment by SamuelCano03** [comment]
Thank you very much sorry for the large debug too
