### ISSUE TITLE
Blank Screen?

### ISSUE THREAD

**Issue by a-rbsn** [barrett-ruth/live-server.nvim#7]
So I managed to install the plugin properly using Packer — but when I ran :LiveServerStart inside my directory it started the server but didn't show the index.html file, am I missing something obvious?

**Comment by barrett-ruth** [comment]
can you add a screenshot/video and more debug information please? It's impossible to know what the issue is given that little info.

**Comment by a-rbsn** [comment]
Apologies — when running the command, the live server boots up and opens the browser, but it's just a blank page — like it wasn't detecting the current folder or something? I'm just using the 'live-server' console command for now

**Comment by barrett-ruth** [comment]
Can I get a screenshot of the browser please?

**Comment by a-rbsn** [comment]
It really is just a blank tab, there's nothing to see? If you need specific details I'd be happy to provide them?

**Comment by barrett-ruth** [comment]
What URL is the tab? is it a blank new tab?
